// GRBL post-processor

export const grbl = {
  id: 'grbl',
  name: 'GRBL',

  header(op) {
    return [
      '; Generated by Swarf.cam',
      `; Post-processor: GRBL`,
      `; Operation: ${op.label} (${op.type})`,
      `; Tool diameter: ${op.toolDiameter} mm`,
      `; Feedrate: ${op.feedrate} mm/min`,
      `; Spindle: ${op.spindleSpeed} RPM`,
      '',
      'G90 G94',        // absolute mode, feedrate in units/min
      'G21',            // millimeters
      `S${op.spindleSpeed} M3`, // spindle on CW
      'G4 P2',          // dwell 2s for spindle spin-up
    ].join('\n')
  },

  footer() {
    return [
      '',
      'M5',    // spindle off
      'G0 Z5', // retract
      'G0 X0 Y0',
      'M30',   // end of program
    ].join('\n')
  },

  rapidTo(x, y, z) {
    const parts = ['G0']
    if (x !== undefined) parts.push(`X${fmt(x)}`)
    if (y !== undefined) parts.push(`Y${fmt(y)}`)
    if (z !== undefined) parts.push(`Z${fmt(z)}`)
    return parts.join(' ')
  },

  linearTo(x, y, z, feed) {
    const parts = ['G1']
    if (x !== undefined) parts.push(`X${fmt(x)}`)
    if (y !== undefined) parts.push(`Y${fmt(y)}`)
    if (z !== undefined) parts.push(`Z${fmt(z)}`)
    if (feed !== undefined) parts.push(`F${feed}`)
    return parts.join(' ')
  },

  comment(text) {
    return `; ${text}`
  },
}

function fmt(n) {
  return n.toFixed(4)
}
