// LinuxCNC post-processor

export const linuxcnc = {
  id: 'linuxcnc',
  name: 'LinuxCNC',

  header(op) {
    return [
      `; Generated by Swarf.cam`,
      `; Post-processor: LinuxCNC`,
      `; Operation: ${op.label} (${op.type})`,
      '',
      'G90 G94 G17',
      'G21',
      `S${op.spindleSpeed} M3`,
      'G4 P2',
    ].join('\n')
  },

  footer() {
    return [
      '',
      'M5',
      'G0 Z5',
      'G0 X0 Y0',
      'M2',
    ].join('\n')
  },

  rapidTo(x, y, z) {
    const parts = ['G0']
    if (x !== undefined) parts.push(`X${fmt(x)}`)
    if (y !== undefined) parts.push(`Y${fmt(y)}`)
    if (z !== undefined) parts.push(`Z${fmt(z)}`)
    return parts.join(' ')
  },

  linearTo(x, y, z, feed) {
    const parts = ['G1']
    if (x !== undefined) parts.push(`X${fmt(x)}`)
    if (y !== undefined) parts.push(`Y${fmt(y)}`)
    if (z !== undefined) parts.push(`Z${fmt(z)}`)
    if (feed !== undefined) parts.push(`F${feed}`)
    return parts.join(' ')
  },

  comment(text) {
    return `; ${text}`
  },
}

function fmt(n) {
  return n.toFixed(4)
}
