// Mach3 post-processor

export const mach3 = {
  id: 'mach3',
  name: 'Mach3',

  header(op) {
    return [
      `%`,
      `O0001`,
      `; Generated by Swarf.cam`,
      `; Post-processor: Mach3`,
      `; Operation: ${op.label} (${op.type})`,
      '',
      'G90 G94 G17',
      'G21',
      `M3 S${op.spindleSpeed}`,
      'G4 P2',
    ].join('\n')
  },

  footer(safeZ = 5) {
    return [
      '',
      'M5',
      `G0 Z${fmt(safeZ)}`,
      'G0 X0 Y0',
      'M30',
      '%',
    ].join('\n')
  },

  rapidTo(x, y, z) {
    const parts = ['G0']
    if (x !== undefined) parts.push(`X${fmt(x)}`)
    if (y !== undefined) parts.push(`Y${fmt(y)}`)
    if (z !== undefined) parts.push(`Z${fmt(z)}`)
    return parts.join(' ')
  },

  linearTo(x, y, z, feed) {
    const parts = ['G1']
    if (x !== undefined) parts.push(`X${fmt(x)}`)
    if (y !== undefined) parts.push(`Y${fmt(y)}`)
    if (z !== undefined) parts.push(`Z${fmt(z)}`)
    if (feed !== undefined) parts.push(`F${feed}`)
    return parts.join(' ')
  },

  comment(text) {
    return `(${text})`
  },
}

function fmt(n) {
  return n.toFixed(4)
}
