import { useEffect } from 'react'

const TOS_CONTENT = (
  <div className="space-y-5">
    <div>
      <h2 className="text-[#e0e0e0] text-base font-bold mb-1">Terms of Service</h2>
      <p className="text-[#555] text-xs">Swarf.cam | Effective Date: June 1, 2026</p>
    </div>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">1. Acceptance of Terms</h3>
      <p className="text-[#999] text-xs leading-relaxed">By accessing or using Swarf.cam you agree to be bound by these Terms of Service. If you do not agree, do not use the app.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">2. Description of Service</h3>
      <p className="text-[#999] text-xs leading-relaxed">Swarf.cam is a free, browser-based CAM (Computer-Aided Manufacturing) application that converts OpenSCAD geometry into G-code for use with CNC milling machines. The service is provided free of charge with no registration required.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">3. No Warranty — Use at Your Own Risk</h3>
      <p className="text-[#999] text-xs leading-relaxed mb-3">SWARF.CAM IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. WE MAKE NO GUARANTEE THAT THE G-CODE GENERATED BY THIS APPLICATION IS ACCURATE, SAFE, OR SUITABLE FOR USE ON ANY PARTICULAR MACHINE OR MATERIAL.</p>
      <p className="text-[#999] text-xs leading-relaxed mb-2">You are solely responsible for:</p>
      <ul className="text-[#999] text-xs leading-relaxed space-y-1 list-disc list-inside ml-2">
        <li>Reviewing and verifying all G-code before running it on any machine</li>
        <li>Ensuring G-code is compatible with your specific CNC controller, firmware, and hardware</li>
        <li>The safe operation of your CNC machine</li>
        <li>Any damage to your machine, tooling, workpiece, or surroundings resulting from the use of G-code generated by this app</li>
        <li>Any personal injury resulting from machine operation</li>
      </ul>
      <p className="text-[#6b9fff] text-xs leading-relaxed mt-3 font-medium">CNC machines are powerful tools capable of causing serious injury and property damage. Never run G-code on hardware without first simulating it in a dedicated G-code simulator and verifying it is safe to run.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">4. Limitation of Liability</h3>
      <p className="text-[#999] text-xs leading-relaxed">To the maximum extent permitted by applicable law, Swarf.cam and its developers shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of this application or any G-code it generates, including but not limited to damage to CNC equipment, tooling, workpieces, or personal injury.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">5. Intellectual Property</h3>
      <p className="text-[#999] text-xs leading-relaxed mb-2">Swarf.cam is open source software released under the MIT License. You are free to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software in accordance with the MIT License terms. The full license is available in the project repository at{' '}
        <a href="https://github.com/deependdesigns/swarf-cam" target="_blank" rel="noopener noreferrer" className="text-[#6b9fff] hover:underline">github.com/deependdesigns/swarf-cam</a>.
      </p>
      <p className="text-[#999] text-xs leading-relaxed mb-2">The underlying OpenSCAD WASM library is licensed separately under GPL-2.0.</p>
      <p className="text-[#999] text-xs leading-relaxed">The G-code and designs you produce using this app are entirely your own. We claim no ownership over anything you create.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">6. Acceptable Use</h3>
      <p className="text-[#999] text-xs leading-relaxed">You agree not to use Swarf.cam in any way that violates applicable laws or regulations. The app is intended for legitimate CNC machining and fabrication purposes.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">7. Changes to the Service</h3>
      <p className="text-[#999] text-xs leading-relaxed">We reserve the right to modify, suspend, or discontinue the service at any time without notice.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">8. Changes to These Terms</h3>
      <p className="text-[#999] text-xs leading-relaxed">We may update these Terms at any time. Continued use of the app after changes constitutes acceptance of the new Terms. The effective date at the top of this page will reflect the most recent update.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">9. Governing Law</h3>
      <p className="text-[#999] text-xs leading-relaxed">These Terms are governed by the laws of the State of Texas, without regard to its conflict of law provisions.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">10. Contact</h3>
      <p className="text-[#999] text-xs leading-relaxed">Questions about these Terms can be directed to the project via the GitHub repository at{' '}
        <a href="https://github.com/deependdesigns/swarf-cam" target="_blank" rel="noopener noreferrer" className="text-[#6b9fff] hover:underline">github.com/deependdesigns/swarf-cam</a>.
      </p>
    </section>
  </div>
)

const PRIVACY_CONTENT = (
  <div className="space-y-5">
    <div>
      <h2 className="text-[#e0e0e0] text-base font-bold mb-1">Privacy Policy</h2>
      <p className="text-[#555] text-xs">Swarf.cam | Effective Date: June 1, 2026</p>
    </div>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">1. Overview</h3>
      <p className="text-[#999] text-xs leading-relaxed mb-2">Swarf.cam is committed to being transparent about how data is handled. This policy explains what information is collected when you use Swarf.cam and how it is used.</p>
      <p className="text-[#6b9fff] text-xs leading-relaxed font-medium">The short version: we do not collect, store, or sell your personal data or your designs. All OpenSCAD code, G-code, and design work you do in Swarf.cam stays in your browser and never touches our servers.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">2. Information We Do Not Collect</h3>
      <ul className="text-[#999] text-xs leading-relaxed space-y-1 list-disc list-inside ml-2 mb-3">
        <li>Your OpenSCAD code or designs</li>
        <li>Your G-code output</li>
        <li>Your machine settings or configurations</li>
        <li>Your name, email, or any account information</li>
        <li>Any files you work with in the app</li>
      </ul>
      <p className="text-[#999] text-xs leading-relaxed">Swarf.cam requires no account creation and no login.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">3. Information Collected by Google Analytics</h3>
      <p className="text-[#999] text-xs leading-relaxed mb-2">Swarf.cam uses Google Analytics to understand how the app is being used. Google Analytics collects:</p>
      <ul className="text-[#999] text-xs leading-relaxed space-y-1 list-disc list-inside ml-2 mb-3">
        <li>Usage data — pages visited, features used, time spent in the app</li>
        <li>Device and browser information — browser type, operating system, screen resolution</li>
        <li>Approximate location — country and region level, derived from your IP address</li>
        <li>IP address — collected by Google, not stored by us</li>
        <li>Referring URL — what site or link brought you to Swarf.cam</li>
      </ul>
      <p className="text-[#999] text-xs leading-relaxed mb-2">This data is collected anonymously and in aggregate. We use it solely to understand how the app is being used and to improve it. We do not use it to identify individual users.</p>
      <p className="text-[#999] text-xs leading-relaxed mb-2">Google Analytics data is governed by Google's Privacy Policy, available at{' '}
        <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[#6b9fff] hover:underline">policies.google.com/privacy</a>.
      </p>
      <p className="text-[#999] text-xs leading-relaxed">To opt out of Google Analytics tracking you can install the{' '}
        <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer" className="text-[#6b9fff] hover:underline">Google Analytics Opt-out Browser Add-on</a>.
      </p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">4. Cookies</h3>
      <p className="text-[#999] text-xs leading-relaxed mb-2">Google Analytics uses cookies to distinguish users and track sessions. These are analytics cookies only. Swarf.cam itself does not set any cookies.</p>
      <p className="text-[#999] text-xs leading-relaxed">By using Swarf.cam you consent to the use of Google Analytics cookies as described above.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">5. Third Party Services</h3>
      <p className="text-[#999] text-xs leading-relaxed mb-2">Swarf.cam is hosted on Cloudflare Pages. Cloudflare may collect basic request metadata such as IP addresses for security and performance purposes. This is governed by{' '}
        <a href="https://www.cloudflare.com/privacypolicy" target="_blank" rel="noopener noreferrer" className="text-[#6b9fff] hover:underline">Cloudflare's Privacy Policy</a>.
      </p>
      <p className="text-[#999] text-xs leading-relaxed">The app uses OpenSCAD WASM, which runs entirely in your browser. No data is sent to any OpenSCAD server.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">6. Children's Privacy</h3>
      <p className="text-[#999] text-xs leading-relaxed">Swarf.cam is not directed at children under the age of 13 and we do not knowingly collect data from children.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">7. Your Rights</h3>
      <p className="text-[#999] text-xs leading-relaxed mb-2">Since we do not collect personal data, there is nothing for us to delete or provide to you. For data collected by Google Analytics, you may exercise your rights through{' '}
        <a href="https://myaccount.google.com" target="_blank" rel="noopener noreferrer" className="text-[#6b9fff] hover:underline">Google's privacy controls</a>.
      </p>
      <p className="text-[#999] text-xs leading-relaxed">If you are located in the European Union, you may have additional rights under GDPR regarding data collected by Google Analytics. Please refer to Google's Privacy Policy for more information.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">8. Changes to This Policy</h3>
      <p className="text-[#999] text-xs leading-relaxed">We may update this Privacy Policy from time to time. The effective date at the top of this page will reflect the most recent update. Continued use of the app after changes constitutes acceptance of the updated policy.</p>
    </section>

    <section>
      <h3 className="text-[#c8c8c8] text-xs font-semibold uppercase tracking-wider mb-2">9. Contact</h3>
      <p className="text-[#999] text-xs leading-relaxed">Questions about this Privacy Policy can be directed to the project via the GitHub repository at{' '}
        <a href="https://github.com/deependdesigns/swarf-cam" target="_blank" rel="noopener noreferrer" className="text-[#6b9fff] hover:underline">github.com/deependdesigns/swarf-cam</a>.
      </p>
    </section>
  </div>
)

export default function LegalModal({ doc, onClose, onSwitch }) {
  useEffect(() => {
    function onKey(e) {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [onClose])

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ backgroundColor: 'rgba(0,0,0,0.75)' }}
      onClick={onClose}
    >
      <div
        className="relative flex flex-col bg-[#111] border border-[#2a2a2a] rounded-lg shadow-2xl w-full max-w-2xl mx-4"
        style={{ maxHeight: '85vh' }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Tab bar */}
        <div className="flex items-center border-b border-[#2a2a2a] shrink-0">
          <button
            onClick={() => onSwitch('tos')}
            className={`px-4 py-3 text-xs font-semibold uppercase tracking-wider transition-colors ${
              doc === 'tos'
                ? 'text-[#6b9fff] border-b-2 border-[#6b9fff] -mb-px'
                : 'text-[#555] hover:text-[#888]'
            }`}
          >
            Terms of Service
          </button>
          <button
            onClick={() => onSwitch('privacy')}
            className={`px-4 py-3 text-xs font-semibold uppercase tracking-wider transition-colors ${
              doc === 'privacy'
                ? 'text-[#6b9fff] border-b-2 border-[#6b9fff] -mb-px'
                : 'text-[#555] hover:text-[#888]'
            }`}
          >
            Privacy Policy
          </button>
          <button
            onClick={onClose}
            className="ml-auto mr-3 text-[#444] hover:text-[#888] transition-colors text-lg leading-none px-1"
            title="Close"
            aria-label="Close"
          >
            ✕
          </button>
        </div>

        {/* Scrollable content */}
        <div className="overflow-y-auto p-6">
          {doc === 'tos' ? TOS_CONTENT : PRIVACY_CONTENT}
        </div>
      </div>
    </div>
  )
}
